service: users
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:*:*:table/*"

functions:
  get:
    handler: handler.get
    events:
      - http:
          path: user/get/{id}
          method: get
  list:
    handler: handler.list
    events:
      - http:
          path: user/list
          method: get
  add:
    handler: handler.add
    events:
      - http:
          path: user/add
          method: post
  update:
    handler: handler.update
    events:
      - http:
          path: user/update/{id}
          method: put
  remove:
    handler: handler.remove
    events:
      - http:
          path: user/remove/{id}
          method: delete

custom:
  # local db for serverless-dynamodb-local
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: users
            sources: [./migrations/users.json]

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
  - serverless-dynamodb-local
